# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uakari}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Amro Mousa}]
  s.date = %q{2011-08-29}
  s.description = %q{Uakari a API wrapper for the MailChimp STS API (1.0), which wraps Amazon SES.}
  s.email = %q{amromousa@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/handlers/uakari_delivery_handler.rb",
    "lib/uakari.rb",
    "rdoc/Uakari.html",
    "rdoc/created.rid",
    "rdoc/index.html",
    "rdoc/lib/uakari_rb.html",
    "rdoc/rdoc.css",
    "test/helper.rb",
    "test/test_uakari.rb",
    "uakari.gemspec"
  ]
  s.homepage = %q{http://github.com/amro/uakari}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Uakari a API wrapper for the MailChimp STS API (1.0)}
  s.test_files = [
    "test/helper.rb",
    "test/test_uakari.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, ["> 0.6.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.0"])
      s.add_runtime_dependency(%q<actionmailer>, [">= 3.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<httparty>, ["> 0.6.0"])
      s.add_dependency(%q<json>, [">= 1.4.0"])
      s.add_dependency(%q<actionmailer>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<httparty>, ["> 0.6.0"])
    s.add_dependency(%q<json>, [">= 1.4.0"])
    s.add_dependency(%q<actionmailer>, [">= 3.0.0"])
  end
end

